name: Build and deploy Angular

on:
  push:
    branches:
      - main
      - feature/*   # optional: support multiple dev branches
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: write   # allow pushing to gh-pages
    pages: write      # allow deployment to GitHub Pages
    id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: ng build --configuration production --base-href "/my-angular-app/"


      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/my-angular-app
